### ISSUE TITLE
请问怎么添加留言，关于等页面。谢谢。

### ISSUE THREAD

**Issue by w-nba** [iTimeTraveler/hexo-theme-hiero#12]
略加修改，多多指教。
https://stonemonkey.top/

**Comment by w-nba** [comment]
谢谢，请问中文时，为什么每页都会显示 关于页面的那张图片，应该如何来修改。

**Comment by iTimeTraveler** [comment]
@w-nba 我不确定是不是主题的bug，我抽空排查一下哈

**Comment by Z4HD** [comment]
@w-nba about页面的`index.md`中除正文外最好只存在如下内容。
``` YAML
---
title: [Your Custom title]
date: 2013/7/13 20:46:25
---
```
你可以试一试，或许有点用。
