### ISSUE TITLE
Adding content to new pages?

### ISSUE THREAD

**Issue by kiarafrobles** [iTimeTraveler/hexo-theme-hiero#22]
I've added the categories, tags and about pages at the top but they have no content. The archives page works fine. What am I missing here?

**Comment by iTimeTraveler** [comment]
Hi, @kiarafrobles .

Here is my hexo demo site source code : https://github.com/iTimeTraveler/hexo-theme-hiero/tree/site-source , Maybe that will be helpful for you.

**Comment by kiarafrobles** [comment]
I checked it out, but I still don't see how to add content to the "categories, tags, and, about" pages. What I have right now is up at → [https://kiarafrobles.github.io](https://kiarafrobles.github.io)

**Comment by iTimeTraveler** [comment]
@kiarafrobles https://github.com/iTimeTraveler/iTimeTraveler.github.io/tree/site This is my site source, you could try to build it.  In fact, I am also confused this question, Sorry. :cry:

**Comment by Z4HD** [comment]
@kiarafrobles I solve your problem !

***

```
# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Header Menu
menu:
  Home: /
  Archives: archives
  Categories: categories
  Tags: tags
  About: about
  YourCostomContent: page'sdirname #Add your content here！
rss: /atom.xml

since: 2016
....
```

Please edit them in hiero's `_config.yml`
