### ISSUE TITLE
大大你好

### ISSUE THREAD

**Issue by yeqingyun** [iTimeTraveler/hexo-theme-hiero#31]
请问主题如何切换语言呢，我看见有一个zh-CN.ym，不知如何切换

**Comment by iTimeTraveler** [comment]
Hello, @yeqingyun 切换语言的地方不在主题里，在Hexo根目录下，也有个`_config.yml` 配置文件。这个是整个站点的配置，在这个文件里有个`language`字段：

```yml
title: iTimeTraveler
subtitle:
description: Someone knock at the door.
author: Mr.Seven
language: zh-CN
timezone: 
```

把这个`language`字段改成`zh-CN`就可以改成中文了，你试试

**Comment by Z4HD** [comment]
请修改您博客根目录下```_config.yml```中的```language: ```字段以切换主题语言。

示例：

``` yaml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: your Blog
subtitle: xxxx
description: xxxxxx
author: Z4HD
language: zh-CN
timezone:
```
