### ISSUE TITLE
图片存在哪的问题？原谅我是小白。。

### ISSUE THREAD

**Issue by supersong95** [iTimeTraveler/hexo-theme-hiero#33]
我想问一下，打赏的图片应该存放到哪里啊，我点击之后没用了，原谅我是小白。。。

**Comment by iTimeTraveler** [comment]
Hello, @supersong95 你可以参考下我的Hexo目录，https://github.com/iTimeTraveler/hexo-theme-hiero/tree/site-source

可以把图片资源放到 `source/gallery` 目录下，然后路径可以写成下面这个样子，你试试：

```yml
wechatImage: /gallery/music1.jpg
```

**Comment by medmin** [comment]
请教一个问题：

logo的路径是：
```
# Put your favicon.ico into `hexo-site/themes/hiero/source/` directory.
favicon: gallery/favicon.ico
```

但wechat打赏的路径是：
```
donate:
    enable: true
    message: '......'
    wechatImage: /gallery/awesomejs_wechat.png
    alipayImage: /gallery/awesomejs_alipay.jpg
```


但其实上，`hexo-site/themes/hiero/source/` directory里面没有`gallery`这个目录。

所以我感觉有点看不懂，虽然是没报错的。

能否指教一下？谢谢
