### ISSUE TITLE
How to show sidebar in the post

### ISSUE THREAD

**Issue by arifpedia** [iTimeTraveler/hexo-theme-hiero#39]
I look this theme using TOC beside a post. How to relpace it with sidebar like in homepage? Thank you

**Comment by iTimeTraveler** [comment]
@arifpedia Sorry, this feature have not been supported. you can just hide the TOC by disabling below field:

```yml
# Post Article's Content
post_catalog:
  enable: false
```
