### ISSUE TITLE
First image for thumbnail and logo image

### ISSUE THREAD

**Issue by Ratne** [iTimeTraveler/hexo-theme-hiero#4]
morning is there a way to show the first picture like the thumbnail? and there is a way to change the logo from text to img?

**Comment by iTimeTraveler** [comment]
@Ratne  hi, morning. Ratne :smile: 

> 1、First image for thumbnail ? 

Sorry, I didn't find relevant API from [Hexo Docs](https://hexo.io/docs/variables.html) about this. In fact , there is a variable `[page.photos]	- The photos of the article (Used in gallery posts)  ` means that. But unfortunately, this variable dose NOT work. :disappointed_relieved:  so I just use the **`photos` field in our Markdown post file** to resolve this problem. 

Just like a header of  Markdown post example from my Hexo source : https://github.com/iTimeTraveler/hexo-theme-hiero/tree/site-source

```
---
title: Being Outside in Fresh Air & How Your Body Loves It
date: 2016-11-20 21:55:38
comments: true
categories:
	- lifeStyle
	- markup
tags:
	- sticky
	- template
photos:
	- gallery/01.jpg
---
```


> 2、 change the logo from text to img?

It's a great idea, Ratne. and it's not complex, so I will find some time to implement this function, and remind you if I have done this. thank you Ratne. :+1:

**Comment by Ratne** [comment]
thank u very much

**Comment by iTimeTraveler** [comment]
ok, @Ratne 

 I have finished this job. you can just `git pull` , and will find a new filed `avatar` was added in `_config.yml` file. 

then just enable `avatar` field like below example:

```yml
# Put your avatar.jpg into `hexo-site/themes/hiero/source/` directory.
# url is target link (E.g. `url: https://hexo.io/logo.svg` or `url: css/images/mylogo.jpg`)
avatar: 
  enable: true
  width: 124
  height: 124
  bottom: 10
  url: https://hexo.io/logo.svg
```
